netbox_e164/urls.py
"""Django urlpatterns declaration for netbox_e164 plugin.

(c) 2020 C Spire Business
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
from django.urls import path, re_path

from .apps import E164AppConfig

from .views import (
    E164NumberListView,
    E164NumberView,
    E164NumberEditView,
    E164NumberBulkDeleteView,
    E164NumberBulkImportView,
    load_partitions,
    load_trunks,
    E164TaskListView,
    E164TaskLogEntryView,
    E164TaskLogEntryViewFiltered,
    E164TaskBulkDeleteView,
    E164SyncRequestView,
    sync_e164,
)

urlpatterns = [
    path("", E164NumberListView.as_view(), name="e164number_list"),
    path("add/", E164NumberView.as_view(), name="e164number_add"),
    path("<int:pk>/edit/", E164NumberEditView.as_view(), name="e164number_edit"),
    path("delete/", E164NumberBulkDeleteView.as_view(), name="e164number_delete"),
    path("import/", E164NumberBulkImportView.as_view(), name="e164number_import"),
    path("ajax/load-partitions/", load_partitions, name="ajax_load_partitions"),
    path("ajax/load-trunks/", load_trunks, name="ajax_load_trunks"),
    path("task/", E164TaskListView.as_view(), name="e164task_list"),
    path("task/delete", E164TaskBulkDeleteView.as_view(), name="e164task_delete"),
    path("task/add", E164SyncRequestView.as_view(), name="e164syncrequest_add"),
    path("task/logentry/", E164TaskLogEntryView.as_view(), name="e164tasklogentry_list"),
    re_path(r"task/logentry/\?task=/d*", E164TaskLogEntryViewFiltered.as_view(), name="e164tasklogentryfiltered_list"),
    path("ajax/sync-ucm/", sync_e164, name="ajax_sync_e164"),
]

# plugin init code, nowhere else to put it for now
E164AppConfig.ready()

netbox_e164/models.py
"""E164Number Django model.

(c) 2020 C Spire Business
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
from django.db import models
from django.core.validators import RegexValidator
from extras.utils import extras_features
from netbox.models import PrimaryModel
from utilities.querysets import RestrictedQuerySet
from netbox_e164.choices import E164TaskStatus, E164TaskTypes, E164TrunkTypes


@extras_features("export_templates", "webhooks")
class E164Number(PrimaryModel):
    """Used to track individual phone numbers."""

    number = models.CharField(
        unique=True, null=False, max_length=50, help_text="Enter number in E.164 format (including +)"
    )

    ucm_uuid = models.UUIDField(unique=True, blank=True, null=True)

    tenant = models.ForeignKey(to="tenancy.Tenant", on_delete=models.PROTECT, blank=True, null=True)

    site = models.ForeignKey(to="dcim.Site", on_delete=models.PROTECT, blank=True, null=True)

    description = models.TextField(blank=True, null=True)

    ucm = models.ForeignKey(to="dcim.Device", on_delete=models.PROTECT, blank=True, null=True)

    partition = models.ForeignKey(to="netbox_e164.E164Partition", on_delete=models.PROTECT, blank=True, null=True)

    trunk = models.ForeignKey(to="netbox_e164.E164Trunk", on_delete=models.PROTECT, blank=True, null=True)

    synced_to_ucm = models.BooleanField(default=False)

    date_last_verified = models.DateTimeField(blank=True, null=True)

    validators = [
        RegexValidator(
            regex=r"^\+?[1-9][\d\[\]-]{1,14}$",
            message="Enter a valid E164 number including the + sign. Follow UCM Wildcard conventions.",
        )
    ]

    objects = RestrictedQuerySet.as_manager()

    csv_headers = [
        "number",
        "tenant",
        "site",
        "description",
        "ucm",
        "partition",
        "trunk",
    ]

    class Meta:
        """Provides default order for class"""

        ordering = ["number"]

    def __str__(self):
        """String representation of an E164 Number"""
        return f"{self.site} : {self.number}"

    def get_absolute_url(self):
        from django.urls import reverse

        return reverse("plugins:netbox_e164:e164number_edit", args=[self.pk])


class E164DeletedNumber(PrimaryModel):
    """Used to track individual phone numbers as they are deleted and removed from UCM."""

    number = models.CharField(
        unique=False, null=False, max_length=50, help_text="Enter number in E.164 format (including +)"
    )

    ucm_uuid = models.UUIDField(blank=True, null=True)

    tenant = models.ForeignKey(to="tenancy.Tenant", on_delete=models.SET_NULL, blank=True, null=True)

    site = models.ForeignKey(to="dcim.Site", on_delete=models.SET_NULL, blank=True, null=True)

    description = models.TextField(blank=True, null=True)

    ucm = models.ForeignKey(to="dcim.Device", on_delete=models.SET_NULL, blank=True, null=True)

    partition = models.ForeignKey(to="netbox_e164.E164Partition", on_delete=models.SET_NULL, blank=True, null=True)

    trunk = models.ForeignKey(to="netbox_e164.E164Trunk", on_delete=models.SET_NULL, blank=True, null=True)

    deleted_on_ucm = models.BooleanField(default=False)

    deleted_on_ucm_date = models.DateTimeField(blank=True, null=True)

    objects = RestrictedQuerySet.as_manager()

    class Meta:
        """Provides default order for class"""

        ordering = ["deleted_on_ucm_date"]

    def __str__(self):
        """String representation of an E164 Number"""
        return f"{self.site} : {self.number}"


class E164Partition(PrimaryModel):
    """Sync'd with UCM for applying to E164Number model"""

    name = models.CharField(max_length=50)

    ucm = models.ForeignKey(to="dcim.Device", on_delete=models.PROTECT, blank=False, null=False)

    ucm_uuid = models.UUIDField(unique=True, blank=True, null=True)

    objects = RestrictedQuerySet.as_manager()

    csv_headers = [
        "name",
        "ucm",
    ]

    class Meta:
        """Provides default order for class"""

        ordering = ["name"]

    def __str__(self):
        """String representation of an E164 Partition"""
        return f"{self.name} : {self.ucm.name}"

    # def get_absolute_url(self):
    #     from django.urls import reverse
    #     return reverse('plugins:netbox_e164:e164partition_edit', args=[self.pk])


class E164Trunk(PrimaryModel):
    """Sync'd with UCM for applying to E164Number model"""

    name = models.CharField(max_length=50, blank=False, null=False)

    type = models.CharField(max_length=255, choices=E164TrunkTypes, blank=False, null=False)

    ucm = models.ForeignKey(to="dcim.Device", on_delete=models.PROTECT, blank=False, null=False)

    ucm_uuid = models.UUIDField(unique=True, blank=True, null=True)

    objects = RestrictedQuerySet.as_manager()

    csv_headers = [
        "name",
        "ucm",
    ]

    class Meta:
        """Provides default order for class"""

        ordering = ["name"]

    def __str__(self):
        """String representation of an E164 Number"""
        return f"{self.name} : {self.ucm.name}"


class E164Task(models.Model):
    """Table used to track synchronization requrests"""

    type = models.CharField(max_length=50, choices=E164TaskTypes)

    device = models.ForeignKey(to="dcim.Device", on_delete=models.PROTECT, blank=False, null=False)

    status = models.CharField(max_length=255, choices=E164TaskStatus, help_text="Overall status of the task")

    created_on = models.DateTimeField(auto_now_add=True)

    STATUS_CLASS_MAP = {
        E164TaskStatus.STATUS_FAILED: "danger",
        E164TaskStatus.STATUS_PENDING: "primary",
        E164TaskStatus.STATUS_RUNNING: "info",
        E164TaskStatus.STATUS_SUCCEEDED: "success",
    }

    def get_status_class(self):
        return self.STATUS_CLASS_MAP.get(self.status)

    class Meta:
        """Provides default order for class"""

        ordering = ["created_on"]

    def __str__(self):
        """String representation of an E164Task"""
        return f"{self.type} : {self.status}"


class E164TaskLogEntry(models.Model):
    """Table used to for event logging"""

    task = models.ForeignKey(to="netbox_e164.E164Task", on_delete=models.CASCADE, blank=False, null=False)

    source = models.CharField(max_length=255)

    message = models.TextField()

    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        """Provides default order for class"""

        ordering = ["created_on"]

    def __str__(self):
        """String representation of an E164TaskLogEntry"""
        return f"{self.source} : {self.message}"

netbox_e164/forms.py
"""Forms for e164 number management.

(c) 2020 C Spire Business
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from django import forms
from django.core.validators import RegexValidator
from django_rq import get_queue
from django.conf import settings

from utilities.forms import BootstrapMixin, CSVModelForm
from extras.forms import CustomFieldModelForm
from tenancy.forms import TenancyForm
from dcim.models import Site, Device
from tenancy.models import Tenant
from extras.forms import CustomFieldModelCSVForm

PLUGIN_SETTINGS = settings.PLUGINS_CONFIG["netbox_e164"]

from .models import E164Number, E164Partition, E164Trunk, E164Task, E164TaskLogEntry

BLANK_CHOICE = (("", "---------"),)


class E164NumberForm(BootstrapMixin, TenancyForm, CustomFieldModelForm):
    """Form for creating or editing an E164Number instance"""

    number = forms.CharField(
        required=True,
        label="E164 Number",
        help_text="Enter number in E.164 format (including +). UCM wildcards are permissable.",
        validators=[
            RegexValidator(
                regex=r"^\+?[1-9][\d\[\]\-X]{1,50}$",
                message="Enter a valid E164 number including the + sign. Follow UCM Wildcard conventions.",
            )
        ],
    )

    site = forms.ModelChoiceField(required=True, queryset=Site.objects.all())

    # tenant = forms.ModelChoiceField(required=True, queryset=Tenant.objects.all())

    description = forms.CharField(required=False, label="Description")

    ucm_role = PLUGIN_SETTINGS["ucm_role"]
    ucm = forms.ModelChoiceField(required=True, queryset=Device.objects.filter(device_role__slug=ucm_role))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        instance = kwargs.get("instance")

        # prime drop downs for existing record
        if instance and instance.ucm is not None:
            initial = kwargs.get("initial", {}).copy()
            initial["ucm"] = instance.ucm
            self.fields["partition"].queryset = E164Partition.objects.filter(ucm=initial["ucm"])
            self.fields["trunk"].queryset = E164Trunk.objects.filter(ucm=initial["ucm"])
        else:
            self.fields["partition"].queryset = E164Partition.objects.none()
            self.fields["trunk"].queryset = E164Trunk.objects.none()

        # prime drop downs for new record on post
        if "ucm" in self.data:
            try:
                ucm_id = int(self.data.get("ucm"))
                self.fields["partition"].queryset = E164Partition.objects.filter(ucm=ucm_id)
                self.fields["trunk"].queryset = E164Trunk.objects.filter(ucm=ucm_id)
            except:
                pass

    class Meta:
        model = E164Number
        fields = ["number", "site", "tenant_group", "tenant", "description", "ucm", "partition", "trunk"]


class E164NumberListFilterForm(BootstrapMixin, forms.ModelForm):
    """Form for filtering E164NumberList instances"""

    site = forms.ModelChoiceField(queryset=Site.objects.all(), required=False, to_field_name="slug")

    tenant = forms.ModelChoiceField(queryset=Tenant.objects.all(), required=False, to_field_name="slug")

    q = forms.CharField(required=False, label="Search")

    class Meta:  # noqa: D106 "Missing docstring in public nested class"
        model = E164Number
        fields = [
            "q",
            "site",
            "tenant",
        ]


class E164NumberCSVForm(CSVModelForm):
    """Form for entering CSV to bulk-import E164Number entries."""

    tenant = forms.ModelChoiceField(
        queryset=Tenant.objects.all(),
        required=True,
        to_field_name="slug",
        help_text="Slug of parent tenant",
        error_messages={"invalid_choice": "Tenant not found",},
    )
    site = forms.ModelChoiceField(
        queryset=Site.objects.all(),
        required=True,
        to_field_name="slug",
        help_text="Slug of parent site",
        error_messages={"invalid_choice": "Site not found",},
    )
    number = forms.CharField(required=True, help_text="E164 Number including + sign")
    description = forms.CharField(required=False, help_text="short description of number usage")

    class Meta:
        model = E164Number
        fields = E164Number.csv_headers

    def save(self, commit=True, **kwargs):
        """Save the model"""

        model = super().save(commit=commit, **kwargs)
        return model


class E164TaskListFilterForm(BootstrapMixin, forms.ModelForm):
    """Form for filtering E164TaskList instances"""

    q = forms.CharField(required=False, label="Search")

    class Meta:
        model = E164Task
        fields = [
            "q",
            "device",
            "type",
            "status",
        ]


class E164TaskLogEntryFilterForm(BootstrapMixin, forms.ModelForm):
    """Form for filtering E164TaskLogEntry instances"""

    q = forms.CharField(required=False, label="Search")

    class Meta:
        model = E164TaskLogEntry
        fields = [
            "q",
            "task",
            "source",
            "message",
        ]

netbox_e164/templates/netbox_e164/e164_number_edit.html
{% extends 'base.html' %}
{% load form_helpers %}
{% load helpers %}

{% block content %}
    <form action="" id="numberForm" data-partitions-url="{% url 'plugins:netbox_e164:ajax_load_partitions' %}" data-trunks-url="{% url 'plugins:netbox_e164:ajax_load_trunks' %}"method="post" enctype="multipart/form-data" class="form form-horizontal">
        {% csrf_token %}
        {% for field in form.hidden_fields %}
            {{ field }}
        {% endfor %}
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <h3>
                    {% if settings.DOCS_ROOT %}
                        <div class="pull-right">
                            <button type="button" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#docs_modal"><i class="fa fa-question"></i></button>
                        </div>
                    {% endif %}
                    {% block title %}{% if obj.pk %}Editing {{ obj_type }} {{ obj }}{% else %}Add a new {{ obj_type }}{% endif %}{% endblock %}
                </h3>
                {% block tabs %}{% endblock %}
                {% if form.non_field_errors %}
                    <div class="panel panel-danger">
                        <div class="panel-heading"><strong>Errors</strong></div>
                        <div class="panel-body">
                            {{ form.non_field_errors }}
                        </div>
                    </div>
                {% endif %}
                {% block form %}
                    <div class="panel panel-default">
                        <div class="panel-heading"><strong>{{ obj_type|capfirst }}</strong></div>
                        <div class="panel-body">
                            {% block form_fields %}
                                {% render_form form %}
                            {% endblock %}
                        </div>
                    </div>
                {% endblock %}
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-md-offset-3 text-right">
                {% block buttons %}
                    {% if obj.pk %}
                        <button type="submit" name="_update" class="btn btn-primary">Update</button>
                    {% else %}
                        <button type="submit" name="_create" class="btn btn-primary">Create</button>
                        <button type="submit" name="_addanother" class="btn btn-primary">Create and Add Another</button>
                    {% endif %}
                    <a href="{{ return_url }}" class="btn btn-default">Cancel</a>
                {% endblock %}
            </div>
        </div>
    </form>
    <script src="/static/jquery/jquery-3.5.1.min.js"></script>
    <script>
        $("#id_ucm").change(function () {
          var form = document.getElementById("numberForm")
          var url = form.getAttribute("data-partitions-url");  // get the url of the `load_cities` view
          var ucmId = $(this).val();  // get the selected country ID from the HTML input

          $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
            data: {
              'ucm': ucmId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
              $("#id_partition").html(data);  // replace the contents of the city input with the data that came from the server
            }
          });
          
          var url = form.getAttribute("data-trunks-url");  // get the url of the `load_cities` view
          
          $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
            data: {
              'ucm': ucmId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
              $("#id_trunk").html(data);  // replace the contents of the city input with the data that came from the server
            }
          });



        });
    </script>
    {% if obj and settings.DOCS_ROOT %}
        {% include 'inc/modal.html' with name='docs' content=obj|get_docs %}
    {% endif %}
{% endblock %}

netbox_e164/templates/netbox_e164/e164_number_list.html
{% extends 'base.html' %}
{% load buttons %}
{% load helpers %}

{% block content %}
<div class="pull-right noprint">
        {% block buttons %}{% endblock %}
        {% if permissions.add and 'add' in action_buttons %}
            {% add_button "plugins:netbox_e164:e164number_add" %}
        {% endif %}
        {% if permissions.add and 'import' in action_buttons %}
            {% import_button "plugins:netbox_e164:e164number_import" %}
        {% endif %}
        {% if 'export' in action_buttons %}
            {% export_button content_type %}
        {% endif %}

</div>
<h1>{% block title %}E164 Numbers{% endblock %}</h1>
<div class="row">
        <div class="col-md-9">
        {% include 'utilities/obj_table.html' with bulk_delete_url="plugins:netbox_e164:e164number_delete" %}
    </div>
        <div class="col-md-3 noprint">
                {% include 'inc/search_panel.html' %}
        </div>
</div>
{% endblock %}

netbox_e164/templates/netbox_e164/e164_syncrequest.html
{% extends 'base.html' %}
{% load buttons %}
{% load helpers %}

{% block content %}
<div id="alert_wrapper">
  
</div>
<div class="pull-right noprint">
        {% block buttons %}{% endblock %}
</div>
<h1>{% block title %}E164 Devices{% endblock %}</h1>
<div class="row">
        <div class="col-md-9">
        {% include 'utilities/obj_table.html' %}
    </div>
</div>
<script src="/static/jquery/jquery-3.5.1.min.js"></script>
<script>
    function ajax_sync_e164(device_id) {
      var url="{% url 'plugins:netbox_e164:ajax_sync_e164' %}"
      $.ajax({
        url: url,
        data: {
          'device_id': device_id
        },
        success: function (data) {
          alert = document.getElementById("alert_wrapper")
          alert.innerHTML = data


        }
      })
    }
</script
{% endblock %}

netbox_e164/templates/netbox_e164/e164_task_list.html
{% extends 'base.html' %}
{% load buttons %}
{% load helpers %}

{% block content %}
<div class="pull-right noprint">
        {% block buttons %}{% endblock %}
</div>
<h1>{% block title %}E164 Tasks{% endblock %}</h1>
<div class="row">
        <div class="col-md-9">
        {% include 'utilities/obj_table.html' with bulk_delete_url="plugins:netbox_e164:e164task_delete" %}
    </div>
        <div class="col-md-3 noprint">
                {% include 'inc/search_panel.html' %}
        </div>
</div>
{% endblock %}

netbox_e164/templates/netbox_e164/e164_task_list_logbutton.html
<a href="/plugins/e164/task/logentry/?task={{ record.pk }}" class="btn btn-default btn-xs" title="Logs">
    <i class="mdi mdi-archive"></i>
</a>

netbox_e164/templates/netbox_e164/e164_task_logentry.html
{% extends 'base.html' %}
{% load buttons %}
{% load helpers %}

{% block content %}
<div class="pull-right noprint">
        {% block buttons %}{% endblock %}
</div>
<h1>{% block title %}E164 Task Logs{% endblock %}</h1>
<div class="row">
        <div class="col-md-9">
        {% include 'utilities/obj_table.html'%}
    </div>
        <div class="col-md-3 noprint">
                {% include 'inc/search_panel.html' %}
        </div>
</div>
{% endblock %}

netbox_e164/templates/netbox_e164/partition_dropdown_list_options.html
<option value="">---------</option>
{% for partition in partitions %}
<option value="{{ partition.pk }}">{{ partition.name }}</option>
{% endfor %}

netbox_e164/templates/netbox_e164/sync_e164.html
<div class="alert alert-success alert-dismissable" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span>&times;</span>
    </button>
    Sync request submitted for {{dev_name}}
</div>

netbox_e164/templates/netbox_e164/trunk_dropdown_list_options.html
<option value="">---------</option>
{% for trunk in trunks %}
<option value="{{ trunk.pk }}">{{ trunk.name }}</option>
{% endfor %}